project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Get Your Script TogethR!"
  bread-crumbs: false
  favicon: "resources/favicon.svg"
  
  navbar:
    logo: "resources/logo.png"
    left:
      # - text: HOME ## Brauchen wir eine HOME? Is identisch mit klicken auf Logo
      #   href: index.qmd
        
      - text: TUTORIALS
        href: content/tutorials/index.qmd

      - text: HOW-TOS
        href: content/how-tos/index.qmd

      - text: SPOTLIGHTS
        href: content/spotlights/index.qmd

      # - text: ABOUT ## Brauchen wir ein ABOUT?
      #   href: about.qmd

  sidebar: 
  # HOW TOS -----------------
    - title: HOW-TOS
      style: floating
      search: true
      collapse-level: 1
      contents: 
        - text: "How Tos"
          href: content/how-tos/index.qmd
        - section: "Einlesen und Speichern"
          href: content/how-tos/01_read_and_save/index.qmd
          contents:
            - content/how-tos/01_read_and_save/read_multiple_files.qmd
        - section: "Aufbereiten"
          href: content/how-tos/02_data_wrangling/index.qmd
          contents:
            - content/how-tos/02_data_wrangling/tst.qmd
        - section: "Analysieren"
          href: content/how-tos/03_analysis/index.qmd
          contents:
            - content/how-tos/03_analysis/tst.qmd
        - section: "Visualisieren"
          href: content/how-tos/04_plotting/index.qmd
          contents:
            - content/how-tos/04_plotting/tst.qmd

  # TUTORIALS -----------------
    - title: Tutorials
      style: floating
      search: true
      contents: 
        - text: "Tutorials"
          href: content/tutorials/index.qmd
        - section: "Reinf√ºhrung in R"
          href: content/tutorials/beginner/index.qmd
          contents:
            - content/tutorials/beginner/Rste-schritte.qmd
            - content/tutorials/beginner/saubR-machen.qmd
        - section: "Fortgeschrittene Themen"
          href: content/tutorials/advanced/index.qmd
          contents:
            - content/tutorials/advanced/reproducible_projects.qmd
    

  # SPOTLIGHTS -----------------
    - title: Spotlights
      style: floating
      search: true
      contents: 
        - text: "Spotlights"
          href: content/spotlights/index.qmd
        - href: content/spotlights/stringr.qmd

format:
  html:
    theme:
      - minty
      - custom.scss
    toc: true
    lang: de-DE
    link-external-icon: true
    link-external-newwindow: true


